[tool.poetry]
name = "nrbehave"
version = "0.1.0"
description = ""
authors = ["d.willems <denis.willems@nrb.be>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
behave = "^1.2.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
